### ISSUE TITLE
Crystal 0.36.1 

### ISSUE THREAD

**Issue by gummybears** [straight-shoota/sass.cr#7]
Hi,
Upgraded to Crystal 0.36.1, did a fresh shards install and ran my tests, got the following error
```
Showing last frame. Use --error-trace for full trace.\

In lib/sass/src/lib_sass.cr:126:80

 126 | fun option_get_input_path = sass_option_get_input_path(opt : SassOptions*) : Char*?
                                                                                    ^
Error: only primitive types, pointers, structs, unions, enums and tuples are allowed in lib declarations, not (Pointer(UInt8) | Nil)
```

Shards yml file
```
name: sprockets
version: 0.2.8
crystal: 0.36.1

license: MIT

dependencies:

  duktape:
    github: jessedoyle/duktape.cr

  sass:
    github: straight-shoota/sass.cr

  coffee-script:
    github: jessedoyle/coffee-script
```
